### ISSUE TITLE
Taller de Flutter

### ISSUE THREAD

**Issue by JuanRudas02** [ISCOUTB/DG-LuxuryRental#2]

**Comment by Omarb200** [comment]
Instalación de Flutter y reconocimiento de su sintaxis y  de algunas de sus funciones básicas que me ayudaran en la implementación del proyecto.

![Image](https://github.com/user-attachments/assets/b24277ec-2f1a-4ef0-b2eb-7fa629415169)

**Comment by JuanRudas02** [comment]
Creacion de plantillas y aplicaciones 
![Image](https://github.com/user-attachments/assets/c93f853b-0a81-4e92-8112-2f8d87e95af9)
