### ISSUE TITLE
Definir Wireframes de toda la aplicación

### ISSUE THREAD

**Issue by JuanRudas02** [ISCOUTB/DG-LuxuryRental#4]

**Comment by Omarb200** [comment]
Este es uno de los objetivos a llegar con el proyecto.

![Image](https://github.com/user-attachments/assets/e164a2e3-6a24-4e44-b5f5-e98290f649b7)

**Comment by JuanRudas02** [comment]
Paleta de colores a utilizar dentro de la plataforma, utilizando el sistema y la plantilla modelada. 

![Image](https://github.com/user-attachments/assets/8ad16ce9-8530-413e-8b35-4ff87ad1236a)
