### ISSUE TITLE
ID: US-000 : Registro de usuario en dart🤖

### ISSUE THREAD

**Issue by Omarb200** [ISCOUTB/DG-LuxuryRental#5]
### Historias de Usuario para el Usuario

**_Descripción_** 
Como nuevo usuario, quiero poder registrarme en el sistema con mi nombre, correo electrónico y contraseña,
Para tener acceso a las funcionalidades de la aplicación y gestionar mis reservas.

**_Criterios de Aceptación:_**

El sistema debe permitir el registro con nombre, correo electrónico y contraseña.
Debe enviar un correo de confirmación después del registro.
El usuario debe poder iniciar sesión con el correo electrónico y la contraseña registrados.

**Comment by Omarb200** [comment]
### Avance de los Criterios de Aceptación : 
![Image](https://github.com/user-attachments/assets/586f6595-14f9-4ff3-b2d5-ca6e08689596)

**Comment by Jhpertuz** [comment]
![Image](https://github.com/user-attachments/assets/6bc9df26-727c-4756-ae48-b6026ca7a345)

**Comment by JuanRudas02** [comment]
Historias de Usuario para el Usuario
Descripción
Como nuevo usuario, quiero poder registrarme en el sistema con mi nombre, correo electrónico y contraseña,
Para tener acceso a las funcionalidades de la aplicación y gestionar mis reservas.

Criterios de Aceptación:

El sistema debe permitir el registro con nombre, correo electrónico y contraseña.
Debe enviar un correo de confirmación después del registro.
El usuario debe poder iniciar sesión con el correo electrónico y la contraseña registrados.

**Comment by jairoserrano** [comment]
adelante
