### ISSUE TITLE
Demo Dashboard 🖥️

### ISSUE THREAD

**Issue by Jhpertuz** [ISCOUTB/DG-LuxuryRental#6]
**Vistas Previas del Dashboard Demo** 

![Image](https://github.com/user-attachments/assets/4d8ffd22-917e-453f-bcb5-90fc1b6ae9fb)
![Image](https://github.com/user-attachments/assets/7d7a970c-62cd-4b05-95b8-f3cfc376477c)

**Comment by Jhpertuz** [comment]
https://github.com/user-attachments/assets/28347840-26eb-4ef2-a500-909a7254a587

**Comment by jairoserrano** [comment]
adelante
